samples:
        A: [data/samples/A_R1.fq.gz, data/samples/A_R2.fq.gz]
        B: [data/samples/B_R1.fq.gz, data/samples/B_R2.fq.gz]
        C: [data/samples/C_R1.fq.gz, data/samples/C_R2.fq.gz]

reference: hg38
